- hosts: "masters"
  become: yes
  gather_facts: yes

  tasks:

    - name: Ensure the registry mirror configuration exists
      lineinfile:
        path: /etc/containerd/config.toml
        insertafter: '\[plugins."io.containerd.grpc.v1.cri".registry.mirrors\]'
        line: '[plugins."io.containerd.grpc.v1.cri".registry.mirrors."10.210.12.195:5022"]'

    - name: Insert the endpoint line
      lineinfile:
        path: /etc/containerd/config.toml
        insertafter: '\[plugins."io.containerd.grpc.v1.cri".registry.mirrors."10.210.12.195:5022"\]'
        line: '  endpoint = ["http://10.210.12.195:5022"]'
